language: android
jdk: oraclejdk8
sudo: required
android:
  components:
     - tools
     - platform-tools
     - build-tools-26.0.0
     - android-25
     - tools
     - sys-img-armeabi-v7a-android-25

env:
  global:
    - API=25 # Android API level 25 by default
    - TAG=google_apis # Google APIs by default, alternatively use default
    - ABI=armeabi-v7a # ARM ABI v7a by default
    - ADB_INSTALL_TIMEOUT=8

before_install:
  - chmod +x gradlew
  - export EMULATOR="system-images;android-${API};${TAG};${ABI}"

install:
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platforms;android-25"
  - echo yes | sdkmanager "$EMULATOR"
