language: android
jdk: oraclejdk8
sudo: required
android:
  components:
     - tools
     - platform-tools
     - build-tools-26.0.0
     - android-25
     - tools

install:
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platforms;android-25"
